import type { ReactNode } from 'react';
import './globals.css';

const navItems = [
  { href: '/', label: 'Home' },
  { href: '/tour', label: 'Tour' },
  { href: '/agents', label: 'Agents' },
  { href: '/status', label: 'Status' }
];

export const metadata = {
  title: 'BlackRoad OS · Demo Showcase',
  description: 'End-to-end sample of the BlackRoad OS surface area'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-surface text-white">
        <div className="mx-auto flex min-h-screen max-w-6xl flex-col px-6 pb-12 pt-8 font-display">
          <header className="flex items-center justify-between border-b border-white/10 pb-4">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-brand-primary to-brand-secondary" />
              <div>
                <p className="text-sm uppercase tracking-[0.18em] text-white/60">BlackRoad OS</p>
                <h1 className="text-xl font-semibold">Demo Showcase</h1>
              </div>
            </div>
            <nav className="flex gap-4 text-sm">
              {navItems.map((item) => (
                <a
                  key={item.href}
                  href={item.href}
                  className="rounded-md px-3 py-2 text-white/80 transition hover:bg-white/5 hover:text-white"
                >
                  {item.label}
                </a>
              ))}
            </nav>
          </header>
          <main className="flex-1 py-8">{children}</main>
          <footer className="mt-8 border-t border-white/10 pt-4 text-sm text-white/60">
            <p>Public demo surface for Core UI, API Gateway, Operator, and Agent Registry.</p>
            <p className="mt-1">JWT optional · SSE live updates · Generated by Demo-Gen-0</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
