name: CI

on:
  push:
    branches: [work]
  pull_request:
    branches: [work]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
