name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@dcf3d7e97ef69269c0839245201c20df33d1b834
        with:
          directory: ./
